SELECT * FROM matches
select * from matches
where away like ('A%');
select * from matches
where away like ('_a%');
select * from matches
where away like ('v%a');
select * from matches
where away like ('%y_');
